spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        default_batch_fetch_size: 100
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
